services:
  - type: web
    name: bibliotheque
    env: php
    buildCommand: ./build.sh
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: APP_KEY
        value: base64:dVt+awiXOXyIEgIHVcrlHHF30m/ky1K1Ip5WB1pO0IQ=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_PORT
        value: "5432"
      - key: DB_SSLMODE
        value: require
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
